
services: #define containers que farão parte da aplicação
  db2: #container do BD
    image: postgres:15 #contaiiner do banco de dados PostgreSQL, sei que é versao 15 pois está na documentação
    container_name: odoo16_db2
    environment: #Define o usuário, a senha e o nome do banco de dados que serão criados quando o container iniciar
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password 
      - POSTGRES_DB=postgres
    volumes: #local em que os dados serao salvos PERSISTENTEMENTE > no host
      - db_data2:/var/lib/postgresql/data
    restart: always #sempre que houver uma interrupção, reiniciar

  odoo2: #container da aplicação odoo
    image: odoo:16.0 #especifica qual imagem do odoo usar. aqui, versão 16
    container_name: odoo16_teste2
    depends_on:
      - db2 #diz ao Docker para só iniciar o Odoo depois que o serviço db estiver pronto
    ports:
      - "8069:8069" #expoe a porta do container para que possa acessá-la no navegador 
    volumes: #mapeia pastas do computador para o contêiner. 
    #para persistir dados e adicionar configurações.
      - odoo_data2:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment: 
    #define variáveis de ambiente que o Odoo usará para se conectar ao BD
      - HOST=db2
      - USER=odoo
      - PASSWORD=odoo_password 
    restart: always

volumes:
  db_data2:
  odoo_data2:

  