name: Construção da imagem docker

on: 
  push:
    branches: [ "main" ]

jobs:
  
  build-and-publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read      
      packages: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Extrair tags para a Imagem
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Construir e Publicar a Imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: . 
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Disparar Deploy no Dokploy
      run: curl -X POST ${{ secrets.DOKPLOY_WEBHOOK_URL }}
