name: Construção da imagem docker

on: 
  push:
    branches: [ "main" ]

jobs:
  
  build-and-publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read      
      packages: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Adicionar tag correta
      run: docker tag odoo:latest ${{ env.IMAGE_NAME }}:latest
    
    - name: Construção da imagem docker
      run: docker compose build odoo
    
    - name: Publicar a Imagem no GHCR
      run: docker push --all-tags ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
