name: Construção da imagem docker

on: 
  push:
    branches: [ "main" ]

jobs:
  
  build-and-publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read      
      packages: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Set image name to lowercase
      run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
    - name: Construção da imagem docker
      run: docker compose build odoo

    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Adicionar tag correta
      run: docker tag odoo:latest ${{ env.IMAGE_NAME }}:latest

    - name: Envia a imagem para o ghcr
      run: docker push ${{ env.IMAGE_NAME}}:latest
