name: Construção da imagem docker

on: 
  push:
    branches: [ "main" ]

env:
    IMAGE_NAME: ghcr.io/${{ tolower(github.repository) }}
    
jobs:
  
  build-and-publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read      
      packages: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Construção da imagem docker
      run: docker compose build odoo

    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Adicionar tag correta
      run: docker tag odoo:latest ${{ env.IMAGE_NAME }}:latest

    - name: Envia a imagem para o ghcr
      run: docker push ${{ env.IMAGE_NAME}}:latest
